"""Behavioral checks for non-destructive migration and PDF provenance."""
from . import support
import hashlib
from pathlib import Path
import tempfile
import unittest

from refslib import grade, images, isolation, layout, linked_documents, manifest, preservation, reading, render, repo, translate
from refslib.store import Store


class Preservation(unittest.TestCase):
    def setUp(self):
        self.temp = tempfile.TemporaryDirectory()
        self.addCleanup(self.temp.cleanup)
        self.root = Path(self.temp.name)
        self.store = Store(self.root / "store")

    def test_original_pdf_outranks_a_publisher_link(self):
        source, alternate = b"%PDF-original", b"%PDF-other"
        entry = {"raw_sha256": self.store.put(source),
                 "paper": {"sha256": self.store.put(alternate)}}
        self.assertEqual(("original-pdf", source), preservation.choose_pdf(entry, self.store))

    def test_a_cdn_error_is_not_a_complete_short_advisory(self):
        self.assertIn("CloudFront", grade.looks_broken(
            "ERROR: The request could not be satisfied", "Request blocked. Generated by cloudfront"))
        self.assertFalse(grade.looks_broken("Testing error handling", "A request blocked by a CDN is a normal test result."))

    def test_translation_job_round_trips_only_fixed_data_fields(self):
        prepared = translate.prepare("这是一篇关于安全问题的技术文章。")
        decoded = isolation.decode(isolation.encode(prepared))
        self.assertEqual(prepared.chunks, decoded.chunks)
        self.assertEqual(prepared.original, decoded.original)

    def test_refresh_invalidates_a_translation_of_different_source_bytes(self):
        entry = {"content_sha256": "old", "translation_sha256": "english", "title_english": "Old title"}
        manifest.apply_acquired_fields(entry, {"content_sha256": "new"})
        self.assertNotIn("translation_sha256", entry)
        self.assertEqual("english", entry["stale_translation_sha256"])
        self.assertNotIn("title_english", entry)

    def test_a_generic_database_redirect_does_not_replace_a_specific_advisory(self):
        record = {"original_url": "https://example.test/CVE-2025-27218", "title": "Database"}
        self.assertIn("absent", reading.capture_fault(record, "Browse all the vulnerabilities in this database."))
        self.assertFalse(reading.capture_fault(record, "CVE-2025-27218 is described in this complete record."))

    def test_a_cve_identifier_in_the_source_title_establishes_article_identity(self):
        record = {"original_url": "https://example.test/CVE-2025-27218",
                  "title": "Technical analysis of CVE-2025-27218"}
        body = "The complete article explains the vulnerable parser and its remediation."
        self.assertFalse(reading.capture_fault(record, body))

    def test_unicode_dashes_in_a_cve_title_still_establish_article_identity(self):
        record = {"original_url": "https://example.test/CVE-2021-42321",
                  "title": "Microsoft Exchange RCE (CVE-2021–42321)"}
        self.assertFalse(reading.capture_fault(record, "Complete technical analysis."))

    def test_a_specific_title_matching_the_canonical_path_establishes_cve_identity(self):
        record = {
            "original_url": ("https://example.test/research/"
                             "advisory-sitecore-rce-via-insecure-deserialization-cve-2021-42237"),
            "title": "Advisory: Sitecore RCE via Insecure Deserialization",
        }
        self.assertFalse(reading.capture_fault(record, "Complete affected-version and remediation details."))

    def test_relative_github_figures_use_the_document_directory(self):
        self.assertEqual("https://raw.githubusercontent.com/owner/repo/main/docs/figure.png",
                         images.resolve("figure.png", "https://github.com/owner/repo/blob/main/docs/readme.md"))
        self.assertEqual("https://raw.githubusercontent.com/owner/repo/" + "a" * 40 + "/image.png",
                         images.resolve("image.png", "https://github.com/owner/repo", "a" * 40))

    def test_repository_link_resolution_keeps_code_literal(self):
        body = "![figure](fig.png)\n\n```markdown\n![example](literal.png)\n```\n"
        fixed = repo.document_links(body, "owner/repo", "a" * 40, "docs/readme.md")
        self.assertIn("/docs/fig.png)", fixed)
        self.assertIn("![example](literal.png)", fixed)

    def test_markdown_file_prose_is_readable_and_translatable_without_changing_listings(self):
        record = {"original_url": "https://github.com/owner/repo/blob/main/Notes.md", "kind": "code"}
        source = '# Notes.md\n\n`owner/repo` at `main`, path `Notes.md`.\n\n````markdown\n# Notes\n\n这是需要翻译的完整技术说明。\n\n```csharp\nint example = 1;\n```\n````\n'
        result = reading.reading_content(record, source)
        self.assertNotIn("````markdown", result)
        self.assertIn("```csharp\nint example = 1;\n```", result)
        self.assertTrue(translate.has_foreign_prose(result))
        self.assertEqual(result, reading.reading_content(record, result))

    def test_slide_transcript_links_gain_their_missing_images_once(self):
        record = {"kind": "slides"}
        source = "\n".join('[Slide](https://files.speakerdeck.com/presentations/known/slide_%d.jpg)' % n for n in range(3))
        result = reading.reading_content(record, source)
        self.assertEqual(3, len(images.urls_in(result)))
        self.assertIn("![Slide 3]", result)
        self.assertEqual(result, reading.reading_content(record, result))

    def test_preserved_slide_links_can_enrich_a_better_hand_import(self):
        links = ["https://files.speakerdeck.com/presentations/known/slide_%d.jpg" % n
                 for n in range(3)]
        record = {"kind": "slides", "slide_images": links}
        source = "A hand-converted deck with intact fenced listings."
        result = reading.reading_content(record, source)
        self.assertEqual(links, reading.slide_image_urls(result))
        self.assertEqual(result, reading.reading_content(record, result))

    def test_a_cve_fallback_preserves_the_complete_record_and_declares_its_scope(self):
        import json
        data = {"dataType": "CVE_RECORD", "cveMetadata": {"cveId": "CVE-2025-12345"},
                "containers": {"cna": {"descriptions": [{"lang": "en", "value": "Published description."}],
                                        "references": [{"url": "https://example.test/advisory"}]}}}
        raw = json.dumps(data).encode()
        result = reading.cve_record(raw, "CVE-2025-12345")
        self.assertIn("community assessments", result["body"])
        self.assertIn('"references"', result["body"])
        self.assertIn("https://example.test/advisory", result["body"])
        with self.assertRaises(ValueError):
            reading.cve_record(raw, "CVE-2025-99999")

    def test_linked_pdf_is_used_when_the_original_is_html(self):
        paper = b"%PDF-paper"
        entry = {"raw_sha256": self.store.put(b"<article>text</article>"),
                 "paper": {"sha256": self.store.put(paper)}}
        self.assertEqual(("linked-paper", paper), preservation.choose_pdf(entry, self.store))

    def test_pdf_staleness_tracks_both_text_and_figures(self):
        entry = {"raw_sha256": "abc"}
        baseline = preservation.pdf_inputs(entry, b"Reading copy")
        self.assertNotEqual(baseline, preservation.pdf_inputs(entry, b"Changed copy"))
        entry["images"] = {"https://example.org/image": {"sha256": "changed"}}
        self.assertNotEqual(baseline, preservation.pdf_inputs(entry, b"Reading copy"))

    def test_layout_rejects_source_directed_paths(self):
        for slug in ("../../file", "/tmp/source", "a/b", ".."):
            with self.assertRaises(ValueError):
                layout.relative({"slug": slug, "grade": "research"})
        self.assertEqual(Path("pdf/research/article.pdf"), layout.relative({"slug": "article", "grade": "research"}, "pdf"))

    def test_recovery_keeps_original_and_full_translation_separate(self):
        record = {"title": "Fixture", "original_url": "https://example.org/fixture",
                  "retrieved_kind": "live", "retrieved_utc": "2026-09-22",
                  "translation": "Entire English text.\n\n```csharp\nvar x = 1;\n```"}
        source = "Texte original.\n\n```csharp\nvar x = 1;\n```"
        published = render.render(record, source)
        self.assertEqual((source, record["translation"]), reading.sections(published))
        english = reading.english_render(record, source)
        self.assertIn(record["translation"], english)
        self.assertNotIn("Texte original.", english)
        self.assertEqual([], render.check_attribution(english))

    def test_summary_does_not_become_source_text(self):
        record = {"title": "Fixture", "original_url": "https://example.org/fixture",
                  "retrieved_kind": "summary", "retrieved_utc": "2026-09-22",
                  "summary": "A short original summary."}
        self.assertEqual(("", ""), reading.sections(render.render(record, depth="metadata")))

    def test_atomic_replacement_has_no_leftover_temporary_file(self):
        target = self.root / "article.pdf"
        preservation.write_bytes(target, b"first")
        preservation.write_bytes(target, b"second")
        self.assertEqual(b"second", target.read_bytes())
        self.assertEqual([target], list(self.root.glob("*")))

    def test_malformed_source_link_does_not_hide_a_publisher_pdf(self):
        page = '<a href="http://[bad">example</a><a href="/paper.pdf">PDF</a>'
        self.assertEqual("https://example.org/paper.pdf",
                         linked_documents.discover(page, "https://example.org/article").primary)

    def test_a_shrug_is_not_a_foreign_language_sentence(self):
        self.assertFalse(translate.has_foreign_prose("A complete English sentence.\n\n¯\\_(ツ)_/¯"))

    def test_refresh_refuses_a_stub_and_missing_listings(self):
        self.assertTrue(reading.refresh_gap("Full article. " * 200, "Short abstract."))
        self.assertTrue(reading.refresh_gap("```csharp\nvar x = 1;\n```", "The prose remains."))
        self.assertEqual("", reading.refresh_gap("Brief source.", "Brief source, with more details."))

    def test_pdf_freshness_ignores_retrieval_timestamp(self):
        entry = {"paper": {"sha256": "held", "retrieved_utc": "2026-09-21"}}
        before = preservation.pdf_inputs(entry, b"text")
        entry["paper"]["retrieved_utc"] = "2026-09-22"
        self.assertEqual(before, preservation.pdf_inputs(entry, b"text"))
